name: Docs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    name: docs tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
